version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
    commands:
      - echo skipped on `date`
  build:
     commands:
       - echo Gradlew Build on `date`
       - java -version
       - echo Building the Docker image...
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp
  post_build:
    commands:
      - echo Build completed on `date`
