version: 0.2
phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  build:
     commands:
       - echo Build started on `date`
       - ./gradlew build --scan
       - ./gradlew test
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp
       - echo Building the Docker image...
       - ls build
       - ls build/libs/
       - sh build.sh
  post_build:
    commands:
      - rm -f  /root/.gradle/caches/modules-2/modules-2.lock
      - rm -fr  /root/.gradle/caches/*/plugin-resolution/
      - echo Building completed on `date`

artifacts:
    files:
      - build/libs/*.jar
cache:
  paths:
    - '/root/.gradle/caches/**/*'
    - '/root/.gradle/wrapper/**/*'

