version: 0.2

phase:
  install:
    runtime-versions:
      docker: 18
      java: correto11
  pre_build:
     commands:
        - echo skiped on `date`
  build:
     commands:
       - echo Build started on `date`
       - gradle clean build -x test
       - echo clean build sucessfull `date`
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp
       - echo Building the Docker image...
       - sh build.sh
  post_build:
    commands:
      - echo Building completed on `date`
      - echo Pushing the Docker image...


artifacts:
    files:
      - /build/libs/*