version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      java: corretto11
  pre_build:
     commands:
        - mkdir /opt/gradle
        - unzip -d /opt/gradle gradle-5.6.3-bin.zip
        - export PATH=$PATH:/opt/gradle/gradle-5.6.3/bin
        - echo skiped on `date`
  build:
     commands:
       - echo Build started on `date`
       - gradle test
       - gradle build
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix
       - docker build -t public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp
       - echo Building the Docker image...
       - ls build
       - ls build/libs/
       - sh build.sh
  post_build:
    commands:
      - echo Building completed on `date`
      - echo Pushing the Docker image...

artifacts:
    files:
      - build/libs/*.jar


