version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - echo install gradle `date`
      - gradle_version=5.4.1
      - wget -c http://services.gradle.org/distributions/gradle-${gradle_version}-all.zip
      - unzip  gradle-${gradle_version}-all.zip -d /opt
      - ln -s /opt/gradle-${gradle_version} /opt/gradle
      - printf "export GRADLE_HOME=/opt/gradle\nexport PATH=\$PATH:\$GRADLE_HOME/bin\n" > /etc/profile.d/gradle.sh
      - source /etc/profile.d/gradle.sh
      - gradle -v

  build:
    commands:
      - echo Build started on `date`
      - echo building gradle
      - gradle install
      - gradle build
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - build/libs/pix-0.1-all.jar