version: '3.8'
services:
  bcb:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-bcb-pix"
    ports:
      - "8082:8082"
    networks:
      - "back-end"
  erp-itau:
    image: "public.ecr.aws/d8b2x5c9/orange-stack-sat-itau-erp"
    ports:
      - "9091:9091"
    networks:
      - "back-end"

  db:
    image: mysql
    container_name: mysql
    security_opt:
      - seccomp:unconfined
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proposta
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - "back-end"

  pix:
    build:
      dockerfile: Dockerfile
      context: .
    image: pix
    container_name: pix
    environment:
      BD_URL: jdbc:mysql://db:3306/pix?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
      BD_USER: root
      BD_PASSWORD: root
      ITAU_URL: http://erp-itau:9091
      BCB_URL: http://bcb:8082
    ports:
      - "8080:8080"
      - "50051:50051"
    depends_on:
      - "db"
      - "erp-itau"
      - "bcb"
    networks:
      - "back-end"

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-volume:/etc/prometheus/
    networks:
      - "back-end"
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
    networks:
      - "back-end"
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

volumes:
  grafana-volume:
  prometheus-volume:
  mysql-volume:

networks:
  back-end:
    driver: bridge