apiVersion: v1
kind: Pod
metadata:
  name: db-pix
  labels:
    mysql: db-pix
spec:
  containers:
    - name: mysql-container
      image: mysql:latest
      ports: 
        - containerPort: 3306
      envFrom:
        - configMapRef:
            name: db-configmap