apiVersion: v1
kind: PersistenceVolume
metadata:
  name: pv-1
spec:
  capacity:
    storage: 10Gi
    accessModes:
      - ReadWriteOnce
  gcePersistenDisk:
    pdName: persistent-volume
  storageClassName: standard
  